### ISSUE TITLE
Voice zh-CN-XiaoxiaoNeural with express-as sentiment is no longer working

### ISSUE THREAD

**Issue by johnwood-wff** [Azure-Samples/Cognitive-Speech-TTS#166] opened 2020-02-10 18:19 UTC
The neural voice zh-CN-XiaoxiaoNeural used with mstts:express-as type="sentiment" in the SSML no longer works - it sounds almost identical to the newscast voice. I had raised this in a support issue and they were able to fix it for a day, but then it reverted back again to being the same as newscast.

Can anybody shed light on why this is happening? Is sentiment expression no longer supported for this voice?

We're using it to generate speech for reading story books, and it was perfect for that. But now the voice has changed we can't use it, it just doesn't sound suitable.

**Comment by boltomli** [comment] 2020-02-11 02:49
I tried eastus endpoint which contains neural. All 3 (no express/sentiment/newscast) types of zh-CN-XiaoxiaoNeural work well and the sentiments sound correct, distinct from each other and expected.

Which endpoint do you use? I think the feature is supported.

**Comment by johnwood-wff** [comment] 2020-02-11 03:16
Thanks for getting back to me. I've tried both centralsouth and westus2...  they're slightly different, but sentiment sounds quite different to what it used to a couple of weeks ago. It fixed itself for a day, and then reverted. This is with the same SSML.

It previously sounded more "whispery", more suitable to the content we're creating. Now it's a lot more enunciated. The fact it has changed makes it difficult for us to edit the long content we've already produced. I have attached a file rendered last week with the same SSML compared to one done today.

Have there been updates to the voice? Should we expect it to change without warning?

[tts_mp3s.zip](https://github.com/Azure-Samples/Cognitive-Speech-TTS/files/4183983/tts_mp3s.zip)

**Comment by szhaomsft** [comment] 2020-02-11 05:52
do you use xiaoxiao to read English content?

**Comment by LomiJA** [comment] 2020-02-11 07:11
Hi, @johnwood-wff , I am a little confused about the root issue, but I think maybe you can try “<prosody rate>” in SSML to make the synthetic slower, like 10% slower by “<prosody rate="-10%">”, and maybe <prosody volume="-10%"> together.  This should make the voice "whispery" again.

**Comment by johnwood-wff** [comment] 2020-02-11 13:34
>> do you use xiaoxiao to read English content?

Yes, we need the accent in this case, and it works well.

>> I think maybe you can try “<prosody rate>” in SSML to make the synthetic slower, like 10% slower by “<prosody rate="-10%">”, and maybe <prosody volume="-10%"> together. This should make the voice "whispery" again.

Yes I have tried that already, but it still isnt the same as it was a couple of weeks ago. The update seems to enunciate everything more clearly - which may be good for certain uses, but for the sentiment (which says gives an air of mystery) it seemed more appropriate the way it used to be.

How often should we expect the voice to change though? Is there somewhere where updates are published so it's a bit more quantifiable? 

Thanks,
John

**Comment by LomiJA** [comment] 2020-02-12 02:33
I got it.  So this issue is caused by the conflict between general development goal and specific usage: when we develop the voice, we are following the comments from language experts, and they are always preferring clearer and understandable synthetic speech, this strategy may cause regression to the real usage like urs.  We will see how to improve the development processing to meet more requirements.

And for the issue now, the voice needs to update for reasons, and it is hard to keep the styles totally the same in each updating.  For your targeted task, I strongly recommend to employ the "Batch API" to hold the voice you need (the past xiaoxiao's voice is kept, and you can bring it back through this), I think the cost is close and the voice will be stable, unless you think it is time to update.

Hoping this can help you.

**Comment by johnwood-wff** [comment] 2020-02-12 03:29
Really appreciate the explanation and suggestion. Do you have a link to the batch API (through REST preferably), and how one specifies a specific version of the voice to use? Being able to stick to one version that isn't changing would be fantastic, as it's quite a large project that will take months to complete.

**Comment by szhaomsft** [comment] 2020-02-12 09:54
batch API is in private preview.  

@johnwood-wff  can u send an email t Custom Voice <customvoice @ microsoft.com>

we can follow up discussion in email

**Comment by Yueying-Liu** [comment] 2020-02-12 13:33
@johnwood-wff  Batch API can get back the previous version. Please note that Long audio API (batch API) will not return the speech output immediately. If your scenario does not need real time response, it's a feasible option. Please send us email to follow up with more details. (customvoice@microsoft.com)

**Comment by johnwood-wff** [comment] 2020-02-12 13:42
Thanks, I've followed up through email. Appreciate your responses.

John

**Comment by szhaomsft** [comment] 2020-02-25 05:33
we have offered a solution to use custom voice.  

close it now

**Closed by szhaomsft** 2020-02-25 05:33 UTC
